package hospital.repository.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
/**
 * JDBC к PostgreSQL. Таблицы создаются при первом подключении.
 * Перед запуском создайте базу, например: {@code CREATE DATABASE hospital;}
 * URL и учётные данные задаются свойствами {@code hospital.jdbc.url},
 * {@code hospital.jdbc.user}, {@code hospital.jdbc.password} (см. {@link hospital.Main}).
 */
public final class JdbcConnectionFactory {
    private final String url;
    private final String user;
    private final String password;
    private boolean schemaInitialized;

    public JdbcConnectionFactory(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException ignored) {
            // JDBC 4+: драйвер может подхватиться через ServiceLoader
        }
    }

    public synchronized Connection getConnection() throws SQLException {
        Connection connection = DriverManager.getConnection(url, user, password);
        if (!schemaInitialized) {
            ensureSchema(connection);
            schemaInitialized = true;
        }
        return connection;
    }

    private static void ensureSchema(Connection connection) throws SQLException {
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS departments ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "name VARCHAR(255) NOT NULL,"
                    + "patient_count INT NOT NULL DEFAULT 0"
                    + ")");
            st.execute("CREATE TABLE IF NOT EXISTS patients ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "full_name VARCHAR(500) NOT NULL,"
                    + "age INT NOT NULL,"
                    + "gender VARCHAR(16) NOT NULL,"
                    + "department_id BIGINT NOT NULL,"
                    + "CONSTRAINT fk_patient_department FOREIGN KEY (department_id) REFERENCES departments(id)"
                    + ")");
        }
    }
}
