package hospital.repository.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class Migration {

    private static final String CREATE_DEPARTMENTS_TABLE =
            "CREATE TABLE IF NOT EXISTS departments (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(255) NOT NULL," +
                    "patient_count INT NOT NULL DEFAULT 0" +
                    ")";

    private static final String CREATE_PATIENTS_TABLE =
            "CREATE TABLE IF NOT EXISTS patients (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "full_name VARCHAR(500) NOT NULL," +
                    "age INT NOT NULL," +
                    "gender VARCHAR(16) NOT NULL," +
                    "department_id BIGINT NOT NULL," +
                    "CONSTRAINT fk_patient_department FOREIGN KEY (department_id) REFERENCES departments(id)" +
                    ")";

    public static void migrate(Connection connection) throws SQLException {
        try (Statement st = connection.createStatement()) {
            st.execute(CREATE_DEPARTMENTS_TABLE);
            st.execute(CREATE_PATIENTS_TABLE);
        }
    }
}